# Generated by Django 2.2.12 on 2023-01-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Instansi')),
                ('nama_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
            ],
        ),
    ]
