# Generated by Django 2.1 on 2019-02-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan',
            name='nama_instansi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Instansi'),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='nama_siswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Siswa'),
        ),
    ]
