# Generated by Django 2.1 on 2019-02-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20190211_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan',
            name='nama_instansi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Instansi'),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='nama_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa'),
        ),
    ]
