# Generated by Django 2.2.12 on 2023-01-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.TextField()),
                ('foto', models.ImageField(upload_to='foto')),
                ('verify', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('kd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.KompetensiDasar')),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.PembimbingSiswa')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.AkunSiswa')),
            ],
        ),
    ]
