# Generated by Django 2.2.9 on 2020-02-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_kompetensidasar'),
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='kd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.KompetensiDasar'),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='foto',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
