# Generated by Django 2.2.12 on 2023-01-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('pimpinan', models.CharField(blank=True, max_length=50, null=True)),
                ('pembimbing', models.CharField(max_length=50, null=True)),
                ('kontak', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('program_keahlian', models.CharField(blank=True, choices=[('RPL', 'RPL'), ('TKJ', 'TKJ')], default=True, max_length=3)),
                ('kuota', models.IntegerField(null=True)),
                ('slot', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Semua', 'Semua'), ('L', 'L'), ('P', 'P')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KompetensiDasar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=4)),
                ('nama', models.CharField(max_length=70)),
                ('jurusan', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pembimbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('jurusan', models.CharField(choices=[('RPL', 'RPL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('jk', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1, null=True)),
                ('kelas', models.CharField(choices=[('RPL', (('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'))), ('TKJ', (('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')))], max_length=15)),
                ('program_ahli', models.CharField(choices=[('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak'), ('Teknik Komputer dan Jaringan', 'Teknik Komputer dan Jaringan')], max_length=30)),
                ('pkl', models.BooleanField(default=False)),
                ('status_judul', models.BooleanField(default=False)),
                ('pembimbing', models.BooleanField(default=False)),
                ('isRapotTuntas', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PembimbingSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing_satu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_satu', to='master.Pembimbing')),
                ('siswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
            ],
        ),
    ]
