# Generated by Django 2.2.1 on 2019-05-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('pimpinan', models.CharField(max_length=50, null=True)),
                ('kontak', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('grup', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], default=True, max_length=3)),
                ('limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembimbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('jurusan', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(choices=[('RPL', (('XI.RPL-1', 'XI.RPL-1'), ('XI.RPL-2', 'XI.RPL-2'), ('XI.RPL-3', 'XI.RPL-3'))), ('TKJ', (('XI.TKJ-1', 'XI.TKJ-1'), ('XI.TKJ-2', 'XI.TKJ-2'), ('XI.TKJ-3', 'XI.TKJ-3'), ('XI.TKJ-4', 'XI.TKJ-4')))], max_length=15)),
                ('program_ahli', models.CharField(choices=[('Teknik Komputer dan Jaringan', 'Teknik Komputer dan Jaringan'), ('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak')], max_length=30)),
                ('pkl', models.BooleanField(default=False)),
                ('status_judul', models.BooleanField(default=False)),
                ('pembimbing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PembimbingSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembimbing_dua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_dua', to='master.Pembimbing')),
                ('pembimbing_satu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_satu', to='master.Pembimbing')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
            ],
        ),
    ]
