# Generated by Django 2.1 on 2019-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('grup', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], default=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pembimbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('jurusan', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(choices=[('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'), ('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')], max_length=15)),
                ('program_ahli', models.CharField(choices=[('Teknik Komputer dan Jaringan', 'Teknik Komputer dan Jaringan'), ('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak')], max_length=30)),
                ('pkl', models.BooleanField(default=False)),
                ('status_judul', models.BooleanField(default=False)),
            ],
        ),
    ]
