# Generated by Django 2.2.9 on 2020-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('RPL', (('XI.RPL-1', 'XI.RPL-1'), ('XI.RPL-2', 'XI.RPL-2'), ('XI.RPL-3', 'XI.RPL-3'))), ('TKJ', (('XI.TKJ-1', 'XI.TKJ-1'), ('XI.TKJ-2', 'XI.TKJ-2'), ('XI.TKJ-3', 'XI.TKJ-3'), ('XI.TKJ-4', 'XI.TKJ-4')))], max_length=15),
        ),
    ]
