# Generated by Django 2.2.12 on 2023-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='program_keahlian',
            field=models.CharField(blank=True, choices=[('RPL', 'RPL'), ('TKJ', 'TKJ'), ('TBSM', 'TBSM')], default=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='kompetensidasar',
            name='jurusan',
            field=models.CharField(choices=[('RPL', 'RPL'), ('TKJ', 'TKJ'), ('TBSM', 'TBSM')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pembimbing',
            name='jurusan',
            field=models.CharField(choices=[('RPL', 'RPL'), ('TKJ', 'TKJ'), ('TBSM', 'TBSM')], max_length=3),
        ),
    ]
