# Generated by Django 2.2.9 on 2020-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200214_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='KompetensiDasar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=4)),
                ('nama', models.CharField(max_length=70)),
                ('jurusan', models.CharField(choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], max_length=3)),
            ],
        ),
    ]
