# Generated by Django 2.2.12 on 2023-01-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20230123_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramKeahlian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=4)),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='instansi',
            old_name='gender',
            new_name='jk',
        ),
        migrations.RemoveField(
            model_name='kompetensidasar',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='pembimbing',
            name='jurusan',
        ),
        migrations.AlterField(
            model_name='instansi',
            name='program_keahlian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ProgramKeahlian'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Kelas'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='program_ahli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ProgramKeahlian'),
        ),
        migrations.AddField(
            model_name='kompetensidasar',
            name='program_keahlian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ProgramKeahlian'),
        ),
        migrations.AddField(
            model_name='pembimbing',
            name='program_keahlian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ProgramKeahlian'),
        ),
    ]
