# Generated by Django 2.1 on 2019-02-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_siswa_pembimbing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingsiswa',
            name='pembimbing',
        ),
        migrations.AddField(
            model_name='pembimbingsiswa',
            name='pembimbing_dua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_dua', to='master.Pembimbing'),
        ),
        migrations.AddField(
            model_name='pembimbingsiswa',
            name='pembimbing_satu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_satu', to='master.Pembimbing'),
        ),
    ]
