# Generated by Django 2.1 on 2019-02-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190213_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('XI.RPL-1', 'XI.RPL-1'), ('XI.RPL-2', 'XI.RPL-2'), ('XI.RPL-3', 'XI.RPL-3'), ('XI.TKJ-1', 'XI.TKJ-1'), ('XI.TKJ-2', 'XI.TKJ-2'), ('XI.TKJ-3', 'XI.TKJ-3'), ('XI.TKJ-4', 'XI.TKJ-4')], max_length=15),
        ),
    ]
