# Generated by Django 2.2.12 on 2021-04-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20210408_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingsiswa',
            name='pembimbing_dua',
        ),
    ]
