# Generated by Django 2.2.12 on 2021-04-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_remove_pembimbingsiswa_pembimbing_dua'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instansi',
            old_name='grup',
            new_name='program_keahlian',
        ),
        migrations.AddField(
            model_name='instansi',
            name='pembimbing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instansi',
            name='pimpinan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
