# Generated by Django 2.2.12 on 2021-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20210413_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instansi',
            old_name='limit',
            new_name='kuota',
        ),
        migrations.AddField(
            model_name='instansi',
            name='gender',
            field=models.CharField(blank=True, choices=[('Semua', 'Semua'), ('L', 'L'), ('P', 'P')], max_length=5, null=True),
        ),
    ]
