# Generated by Django 2.1 on 2019-03-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20190315_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='instansi',
            name='email',
            field=models.EmailField(max_length=80, null=True),
        ),
    ]
