# Generated by Django 2.2.12 on 2021-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20210413_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='instansi',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
