# Generated by Django 2.2.12 on 2021-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_instansi_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
