# Generated by Django 2.2.12 on 2021-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20210414_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='program_keahlian',
            field=models.CharField(blank=True, choices=[('TKJ', 'TKJ'), ('RPL', 'RPL')], default=True, max_length=3),
        ),
    ]
