# Generated by Django 2.2.12 on 2021-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20210427_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='slot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
