# Generated by Django 2.2.12 on 2022-06-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_siswa_israpottuntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingsiswa',
            name='siswa',
        ),
        migrations.AddField(
            model_name='pembimbingsiswa',
            name='instansi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Instansi'),
        ),
        migrations.AlterField(
            model_name='instansi',
            name='program_keahlian',
            field=models.CharField(blank=True, choices=[('RPL', 'RPL'), ('TKJ', 'TKJ')], default=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='pembimbing',
            name='jurusan',
            field=models.CharField(choices=[('RPL', 'RPL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('RPL', (('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'))), ('TKJ', (('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')))], max_length=15),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='program_ahli',
            field=models.CharField(choices=[('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak'), ('Teknik Komputer dan Jaringan', 'Teknik Komputer dan Jaringan')], max_length=30),
        ),
    ]
