# Generated by Django 2.2.12 on 2022-06-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20220627_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembimbingsiswa',
            name='instansi',
        ),
        migrations.AddField(
            model_name='pembimbingsiswa',
            name='siswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Siswa'),
        ),
    ]
