# Generated by Django 2.1 on 2019-02-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('akun', '0002_akunsiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='nama_belakang',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='nama_depan',
        ),
        migrations.AddField(
            model_name='akun',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Pembimbing'),
        ),
        migrations.AlterField(
            model_name='akunsiswa',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Siswa'),
        ),
    ]
