# Generated by Django 2.1 on 2019-02-12 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
        ('akun', '0003_auto_20190212_0719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Akun',
            new_name='AkunPembimbing',
        ),
    ]
