# Generated by Django 2.2.4 on 2019-08-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '__first__'),
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionJudul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tanggal_acc', models.DateTimeField(null=True)),
                ('submit_status', models.BooleanField()),
                ('status', models.CharField(max_length=12, null=True)),
                ('catatan', models.TextField(null=True)),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.PembimbingSiswa')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.AkunSiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Bimbingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.CharField(choices=[('BAB I', 'BAB I'), ('BAB II', 'BAB II'), ('BAB III', 'BAB III'), ('BAB IV', 'BAB IV'), ('BAB V', 'BAB V')], max_length=7)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('berkas', models.FileField(upload_to='berkas/')),
                ('status', models.BooleanField(default=True)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karya_ilmiah.SubmissionJudul')),
                ('pembimbing', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='master.PembimbingSiswa')),
                ('siswa', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='akun.AkunSiswa')),
            ],
        ),
    ]
