# Generated by Django 2.1 on 2019-02-14 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0004_auto_20190212_0721'),
        ('master', '0004_auto_20190213_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionJudul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tanggal_acc', models.DateTimeField(null=True)),
                ('submit_status', models.BooleanField()),
                ('status', models.CharField(max_length=12, null=True)),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.PembimbingSiswa')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.AkunSiswa')),
            ],
        ),
    ]
