# Generated by Django 2.2.9 on 2020-01-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
        ('master', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionJudul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tanggal_acc', models.DateTimeField(null=True)),
                ('submit_status', models.BooleanField()),
                ('status', models.CharField(max_length=12, null=True)),
                ('catatan', models.TextField(null=True)),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.PembimbingSiswa')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.AkunSiswa')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.AkunPembimbing')),
            ],
        ),
        migrations.CreateModel(
            name='Bimbingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.CharField(choices=[('BAB I', 'BAB I'), ('BAB II', 'BAB II'), ('BAB III', 'BAB III'), ('BAB IV', 'BAB IV')], max_length=7)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('berkas', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('Selesai', 'Selesai'), ('Review', 'Review'), ('Revisi', 'Revisi')], default='Review', max_length=12)),
                ('catatan', models.TextField(default=None, null=True)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karya_ilmiah.SubmissionJudul')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.AkunPembimbing')),
            ],
        ),
    ]
