# Generated by Django 2.1 on 2019-02-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionjudul',
            name='catatan',
            field=models.TextField(null=True),
        ),
    ]
