# Generated by Django 2.2.4 on 2019-08-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimbingan',
            name='pembimbing',
        ),
        migrations.RemoveField(
            model_name='bimbingan',
            name='siswa',
        ),
        migrations.AlterField(
            model_name='bimbingan',
            name='bab',
            field=models.CharField(choices=[('BAB I', 'BAB I'), ('BAB II', 'BAB II'), ('BAB III', 'BAB III'), ('BAB IV', 'BAB IV')], max_length=7),
        ),
        migrations.AlterField(
            model_name='bimbingan',
            name='status',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Review', 'Review'), ('Revisi', 'Revisi')], default='Review', max_length=12),
        ),
    ]
