# Generated by Django 2.1 on 2019-02-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0002_submissionjudul_catatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimbingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.CharField(choices=[('BAB I', 'BAB I'), ('BAB II', 'BAB II'), ('BAB III', 'BAB III'), ('BAB IV', 'BAB IV'), ('BAB V', 'BAB V')], max_length=7)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('berkas', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=7)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karya_ilmiah.SubmissionJudul')),
            ],
        ),
    ]
