# Generated by Django 2.2.4 on 2019-08-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0002_auto_20190821_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbingan',
            name='catatan',
            field=models.TextField(null=True),
        ),
    ]
