# Generated by Django 2.1 on 2019-02-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_auto_20190212_0721'),
        ('master', '0006_auto_20190225_0821'),
        ('karya_ilmiah', '0003_bimbingan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbingan',
            name='pembimbing',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='master.PembimbingSiswa'),
        ),
        migrations.AddField(
            model_name='bimbingan',
            name='siswa',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='akun.AkunSiswa'),
        ),
    ]
