# Generated by Django 2.1 on 2019-02-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0004_auto_20190225_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimbingan',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
