# Generated by Django 2.2.4 on 2019-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0007_auto_20190822_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimbingan',
            name='berkas',
            field=models.FileField(upload_to='berkas/'),
        ),
    ]
