# Generated by Django 2.2.4 on 2019-09-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('karya_ilmiah', '0009_auto_20190822_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionjudul',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Pembimbing'),
        ),
    ]
