# Generated by Django 2.2.4 on 2019-09-23 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0010_submissionjudul_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionjudul',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.AkunPembimbing'),
        ),
    ]
